//! Autostart on login via a systemd user unit
//! (`~/.config/systemd/user/wavesink.service`), anchored to
//! `graphical-session.target` so it starts after PipeWire is up.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::error::SinkError;

const UNIT_NAME: &str = "wavesink.service";
const LEGACY_UNIT_NAME: &str = "sink.service";
const LEGACY_HEADER: &str = "# Generated by Sink";

fn unit_path(name: &str) -> Result<PathBuf, SinkError> {
    let dir = crate::persistence::config_root()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir.join("systemd").join("user").join(name))
}

fn render_unit() -> Result<String, SinkError> {
    let exe = std::env::current_exe()
        .map_err(|e| SinkError::Config(format!("cannot resolve own executable path: {e}")))?;
    // Quote for systemd's unit syntax so paths with spaces (or quotes -
    // however unlikely) don't split into command + arguments.
    let exe = format!(
        "\"{}\"",
        exe.display()
            .to_string()
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
    );
    // Boot to tray on login when the user asked for it. Only the autostart
    // launch carries this flag, so manual launches still show the window.
    let exe = if crate::persistence::prefs::Prefs::load().start_minimized {
        format!("{exe} --minimized")
    } else {
        exe
    };
    Ok(format!(
        "# Generated by WaveSink. Re-enabling autostart rewrites this file,\n\
         # so the path tracks wherever the binary currently lives.\n\
         [Unit]\n\
         Description=WaveSink audio mixer\n\
         After=graphical-session.target pipewire.service wireplumber.service\n\
         PartOf=graphical-session.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         ExecStart={}\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         \n\
         [Install]\n\
         WantedBy=graphical-session.target\n",
        exe
    ))
}

fn systemctl(args: &[&str]) -> Result<std::process::Output, SinkError> {
    Command::new("systemctl")
        .arg("--user")
        .args(args)
        .output()
        .map_err(|e| SinkError::Config(format!("systemctl --user {}: {e}", args.join(" "))))
}

fn run_systemctl(args: &[&str]) -> Result<(), SinkError> {
    let out = systemctl(args)?;
    if out.status.success() {
        return Ok(());
    }
    Err(SinkError::Config(format!(
        "systemctl --user {} failed: {}",
        args.join(" "),
        String::from_utf8_lossy(&out.stderr).trim()
    )))
}

/// Replace only legacy units generated by Sink. User-authored units sharing
/// the old name remain untouched.
pub fn migrate_legacy_unit() -> Result<(), SinkError> {
    let legacy = unit_path(LEGACY_UNIT_NAME)?;
    let Ok(raw) = fs::read_to_string(&legacy) else {
        return Ok(());
    };
    if !raw.starts_with(LEGACY_HEADER) {
        return Ok(());
    }

    let was_enabled = systemctl(&["is-enabled", LEGACY_UNIT_NAME])?
        .status
        .success();

    let path = unit_path(UNIT_NAME)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    crate::persistence::write_atomic(&path, render_unit()?)?;
    run_systemctl(&["daemon-reload"])?;
    if was_enabled {
        run_systemctl(&["enable", UNIT_NAME])?;
        run_systemctl(&["disable", LEGACY_UNIT_NAME])?;
    }
    fs::remove_file(legacy)?;
    run_systemctl(&["daemon-reload"])?;
    Ok(())
}

pub fn is_enabled() -> bool {
    if let Err(error) = migrate_legacy_unit() {
        eprintln!("wavesink: autostart migration failed: {error}");
    }
    systemctl(&["is-enabled", UNIT_NAME])
        .map(|out| out.status.success())
        .unwrap_or(false)
}

pub fn enable() -> Result<(), SinkError> {
    migrate_legacy_unit()?;
    let path = unit_path(UNIT_NAME)?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    crate::persistence::write_atomic(&path, render_unit()?)?;

    for step in [&["daemon-reload"][..], &["enable", UNIT_NAME][..]] {
        run_systemctl(step)?;
    }
    Ok(())
}

pub fn disable() -> Result<(), SinkError> {
    migrate_legacy_unit()?;
    let out = systemctl(&["disable", UNIT_NAME])?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        // Disabling a unit that was never enabled is fine.
        if !stderr.contains("does not exist") {
            return Err(SinkError::Config(format!(
                "systemctl --user disable failed: {}",
                stderr.trim()
            )));
        }
    }
    let path = unit_path(UNIT_NAME)?;
    if path.exists() {
        fs::remove_file(&path)?;
        let _ = systemctl(&["daemon-reload"]);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_renders_with_exe_and_session_anchor() {
        let unit = render_unit().expect("renders");
        assert!(unit.contains("[Unit]"));
        assert!(unit.starts_with("# Generated by WaveSink"));
        assert!(unit.contains("Description=WaveSink audio mixer"));
        // Path is quoted so spaces don't split into command + args.
        assert!(unit.contains("ExecStart=\"/"));
        assert!(unit.contains("WantedBy=graphical-session.target"));
        assert!(unit.contains("After=graphical-session.target pipewire.service"));
    }
}
