//! Retires the conf fragment earlier versions rendered rules into: it could
//! only match stream props, and only acted before the enforcer's first pass.

use std::path::{Path, PathBuf};

use crate::error::SinkError;

/// How every fragment an earlier version wrote begins.
const GENERATED_HEADER: &str = "# Generated by Sink";

pub fn conf_path() -> Result<PathBuf, SinkError> {
    let dir = crate::persistence::config_root()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir
        .join("wireplumber")
        .join("wireplumber.conf.d")
        .join("90-sink-routing.conf"))
}

/// Remove a fragment left by an earlier version, if any.
pub fn remove_stale() {
    if let Ok(path) = conf_path() {
        remove_stale_at(&path);
    }
}

/// A file of that name the user wrote themselves is theirs to keep.
fn remove_stale_at(path: &Path) {
    let Ok(raw) = std::fs::read_to_string(path) else {
        return;
    };
    if !raw.starts_with(GENERATED_HEADER) {
        eprintln!(
            "wavesink: leaving {} alone: not one of ours",
            path.display()
        );
        return;
    }
    if let Err(e) = std::fs::remove_file(path) {
        eprintln!("wavesink: removing stale {}: {e}", path.display());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("sink-wp-{}-{name}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        dir.join("90-sink-routing.conf")
    }

    #[test]
    fn removes_the_fragment_an_earlier_version_wrote() {
        let path = scratch("ours");
        std::fs::write(
            &path,
            "# Generated by Sink (audio mixer). Do not edit - regenerated on every\n# routing change.\nstream.rules = []\n",
        )
        .expect("writes");
        remove_stale_at(&path);
        assert!(!path.exists());
    }

    #[test]
    fn keeps_a_file_the_user_wrote() {
        let path = scratch("theirs");
        std::fs::write(&path, "stream.rules = [ { matches = [] } ]\n").expect("writes");
        remove_stale_at(&path);
        assert!(path.exists());
    }

    #[test]
    fn a_missing_file_is_nothing_to_do() {
        remove_stale_at(&scratch("missing"));
    }
}
